# Generated by Django 3.0 on 2021-02-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='imagefile',
            field=models.FileField(null=True, upload_to='screenshots/', verbose_name=''),
        ),
    ]
