# Generated by Django 3.0 on 2021-02-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210218_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='screenshots/', verbose_name=''),
        ),
    ]
