# Generated by Django 3.0 on 2021-02-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='screenshots/'),
        ),
    ]
