# Generated by Django 3.0 on 2021-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210219_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='imagefile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
