# Generated by Django 3.0 on 2021-02-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210219_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='sspic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
