# Generated by Django 3.0 on 2021-02-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_screenshot_sspic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='sspic',
            field=models.ImageField(blank=True, null=True, upload_to='sign-s3/'),
        ),
    ]
