# Generated by Django 3.0 on 2021-02-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210223_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='sspic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
